name: HundredX Continuous Integration

# Triggers
on:
  push:
    tags:
     - '*'
  pull_request:
  workflow_dispatch:

# Jobs
jobs:
  build:
    runs-on: windows-2022
      
    # Job steps  
    steps:    

    # Checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    # Upload static files
    - name: Upload SQL Scripts
      uses: actions/upload-artifact@v4
      with:
        name: SQL
        path: SQLScripts/

    # Setup build enviroment
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build the solution
    - name: Build Solution
      run: msbuild HundredX.sln /P:Configuration=Release /P:Platform="Mixed Platforms" /T:Restore /T:Build /V:m

    # Publish and upload HundredX.API and HundredX.API.IntegrationTests projects
    - name: Publish HundredX.API
      run: msbuild "HundredX.API\HundredX.API.csproj" /P:Configuration=Release /P:Platform=AnyCPU /P:PublishDir="..\bin\API" /P:SelfContained=false /R /T:Build /T:Publish /V:m

    - name: Upload HundredX.API
      uses: actions/upload-artifact@v4
      with:
        name: HundredX.API
        path: bin/API/

    - name: Publish HundredX.API.IntegrationTests
      run: msbuild "HundredX.API.IntegrationTests\HundredX.API.IntegrationTests.csproj" /P:Configuration=Release /P:Platform=AnyCPU /P:PublishDir="..\bin\API.Tests" /P:SelfContained=false /R /T:Build /T:Publish /V:m

    - name: Upload HundredX.API.IntegrationTests
      uses: actions/upload-artifact@v4
      with:
        name: HundredX.API.IntegrationTests
        path: bin/API.Tests/

    # Run Tests
    - name: Run Integration Tests
      run: |
        cd bin/API.Tests
        dotnet vstest HundredX.API.IntegrationTests.dll --logger:trx --ResultsDirectory:TestResults

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: bin/API.Tests/TestResults/


    # Publish and upload console 
    - name: Publish consoleapp1
      run: msbuild "consoleapp1\consoleapp1.csproj" /P:Configuration=Release /P:Platform=AnyCPU /P:PublishDir="..\bin\consoleapp1" /P:SelfContained=false /R /T:Build /T:Publish /V:m

    - name: Upload console app
      uses: actions/upload-artifact@v4
      with:
        name: consoleapp1
        path: bin/consoleapp1/
