name: HundredX Continuous Integration

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # (Optional) sanity check so we fail fast if SQLScripts is missing/empty
      - name: Verify SQLScripts exists and is non-empty
        shell: pwsh
        run: |
          if (-not (Test-Path SQLScripts) -or (Get-ChildItem SQLScripts -Recurse | Measure-Object).Count -eq 0) {
            Write-Host "SQLScripts/ is missing or empty. If this is expected, remove this step."
          }

      # Upload static files
      - name: Upload SQL Scripts
        uses: actions/upload-artifact@v4
        with:
          name: SQL
          path: SQLScripts/
          if-no-files-found: warn

      # Setup build environment
      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Build the solution
      - name: Build Solution
        run: msbuild HundredX.sln /P:Configuration=Release /P:Platform="Mixed Platforms" /T:Restore /T:Build /V:m

      # Publish and upload HundredX.API and HundredX.API.IntegrationTests projects
      - name: Publish HundredX.API
        run: msbuild "HundredX.API\HundredX.API.csproj" /P:Configuration=Release /P:Platform=AnyCPU /P:PublishDir="..\bin\API" /P:SelfContained=false /R /T:Build /T:Publish /V:m

      - name: Upload HundredX.API
        uses: actions/upload-artifact@v4
        with:
          name: HundredX.API
          path: bin/API/

      - name: Publish HundredX.API.IntegrationTests
        run: msbuild "HundredX.API.IntegrationTests\HundredX.API.IntegrationTests.csproj" /P:Configuration=Release /P:Platform=AnyCPU /P:PublishDir="..\bin\API.Tests" /P:SelfContained=false /R /T:Build /T:Publish /V:m

      - name: Upload HundredX.API.IntegrationTests
        uses: actions/upload-artifact@v4
        with:
          name: HundredX.API.IntegrationTests
          path: bin/API.Tests/

      # Publish and upload console app
      - name: Publish consoleapp1
        run: msbuild "consoleapp1\consoleapp1.csproj" /P:Configuration=Release /P:Platform=AnyCPU /P:PublishDir="..\bin\consoleapp1" /P:SelfContained=false /R /T:Build /T:Publish /V:m

      - name: Upload console app
        uses: actions/upload-artifact@v4
        with:
          name: consoleapp1
          path: bin/consoleapp1/
